all:
    children:
        my_root_hosts:
            hosts:
                host1:
                    ansible_host: 192.168.57.2
                    ansible_user: root
                    ansible_ssh_pass: root

                host2:
                    ansible_host: 192.168.57.3
                    ansible_user: root
                    ansible_ssh_pass: root
                                
        web:
            children:
                apache:
                    hosts:
                        host3:
                            ansible_host: 192.168.57.2
                            ansible_user: admin
                nginx:
                    hosts:
                        host4:
                            ansible_host: 192.168.57.3
                            ansible_user: admin
