{
 "title": "lucasHidalgoHerreraAPI",
 "description": "Basic overview of linux host metrics, based on node_exporter",
 "tags": [
  "linux",
  "node-exporter",
  "ops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "%Heap Usage (LHH)",
   "type": "gauge",
   "description": "Determina el porcentaje de MB usados del heap.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_heap_size_used_bytes{instance=~\"host.docker.internal:3000\"})/(nodejs_heap_size_total_bytes{instance=~\"host.docker.internal:3000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Capacity (LHH)",
   "type": "timeseries",
   "description": "Determina la capacidad máxima del heap",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"host.docker.internal:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU Usage (LHH)",
   "type": "timeseries",
   "description": "Mide el porcentaje de uso de CPU en los últimos 5 minutos.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"host.docker.internal:3000\"}[5m]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Duration request (LHH)",
   "type": "barchart",
   "description": "Muestra, por minuto, el numero de peticiones que se realizaron en los últimos 5 minutos, por debajo del tiempo:\n- +Inf\n- 0.003s\n- 0.03s\n- 0.1s\n- 0.3s\n- 1.5s\n- 10s\nEn ese orden.",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_seconds_bucket{instance=~\"host.docker.internal:3000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}