.TH "Racional.h" 3 "Martes, 17 de Octubre de 2023" "Clase Racional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Racional.h \- Fichero cabecera del TDA \fBRacional\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRacional\fP"
.br
.RI "T\&.D\&.A\&. \fBRacional\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBRacional\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Clase Racional del código fuente\&.
