.TH "repConjunto" 3 "Martes, 17 de Octubre de 2023" "Clase Racional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repConjunto \- Rep del TDA \fBRacional\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIrep\&.den!=0\fP 
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBRacional\fP representa al valor
.PP
(rep\&.num,rep\&.den) 
