{
 "title": "lucasHidalgoHerreraLinux",
 "description": "Basic overview of linux host metrics, based on node_exporter",
 "tags": [
  "linux",
  "node-exporter",
  "ops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(instance)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   },
   {
    "name": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Medidas generales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processors (LHH)",
   "type": "stat",
   "description": "Número de procesadores del sistema",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Net IN (LHH)",
   "type": "stat",
   "description": "Cantidad de taos recibidos de la red en 24 horas",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "RAM(LHH)",
   "type": "stat",
   "description": "Memoria RAM del sistema.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "%Disk Usage (LHH)",
   "type": "gauge",
   "description": "Mide el porcentaje de almacenamiento del disco que se ha ocupado.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes{instance=~\"$host\"}) / sum(node_filesystem_size_bytes{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "%Memory Use (LHH)",
   "type": "gauge",
   "description": "Representa el porcentaje de memoria usada en el sistema.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes{instance=~\"$host\",job=~\"$job\"} / node_memory_MemTotal_bytes{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "SSHD active (LHH)",
   "type": "stat",
   "description": "Determina si el servicio SSHD está actvo o no.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"sshd.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (LHH)",
   "type": "stat",
   "description": "Tiempo desde el último arraque.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Net OUT (LHH)",
   "type": "stat",
   "description": "Cantidad de datos emitidos a la red en 24 horas",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$host\"}[1m]))"
    }
   ]
  },
  {
   "title": "%SWAP Used (LHH)",
   "type": "gauge",
   "description": "Porcentaje de memoria swap usado por el sistema (0 es habitual).",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "%Sys Load (LHH)",
   "type": "gauge",
   "description": "Carga general del sistema.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) *100/ count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Apache HTTPD active (LHH)",
   "type": "stat",
   "description": "Determina si el servicio Apache HTTPD está actvo o no.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"httpd.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU Load Total (LHH)",
   "type": "timeseries",
   "description": "Mide el porcentaje medio de uso de CPU por instancia y procesador a lo largo del tiempo. ",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 11 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance, cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "%CPU Time USage(LHH)",
   "type": "bargauge",
   "description": "Determina:\n- Porcentaje medio de tiempo que se ha usado la cpu en los últimos 15 minutos",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[15m])))\n",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Disk (LHH)",
   "type": "table",
   "description": "Información general sobre las particiones del sistema.",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 22 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load Per Mode(LHH)",
   "type": "timeseries",
   "description": "Mide la tasa de uso de CPU de cada uno de los modos (idle, user, system, iowait, softirq).\n- Idle: tiempo ocioso.\n- user: tiempo usado por el usuario.\n- system: tiempo usado por el sistema.\n- iowait: tiempo usado en entrada salida.\n- softirq: riempo manejando interrupciones.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 28 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$host\"}[15m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "% Cores Usage (LHH)",
   "type": "timeseries",
   "description": "Mide la tasa de uso de cada procesador.",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 36 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$host\", mode=~\"user|system|irq|softirq|nice\"}[15m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores in IDLE (LHH)",
   "type": "timeseries",
   "description": "Mide la tasa de inactividad de cada procesador",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 42 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$host\", mode=~\"idle\"}[15m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory (LHH)",
   "type": "graph",
   "description": "Describe información básica de memoria como memoria total, memoria disponible y memoria libre.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Details | $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Free (LHH)",
   "type": "timeseries",
   "description": "Representa la cantidad de memoria libre de cada filesystem.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 56 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"(tmpfs|rootfs)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Activity (LHH)",
   "type": "graph",
   "description": "Describe el movimiento de datos dentro del disco, bytes leídos y bytes escritos.",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 56 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[5m]) ",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) ",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk IO (LHH)",
   "type": "graph",
   "description": "Describe la media de datos leídos y escritos por segundo.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 56 },
   "repeat": "host",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m]) ",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m]) < 0",
     "legendFormat": "Write ({{device}})"
    }
   ]
  }
 ]
}